In [1]:
import pandas as pd

In [5]:
from pandas_profiling import ProfileReport

In [2]:
shark = pd.read_csv(r'C:\Users\rober\Desktop\code study\projetos\shark_attk_projet_1\attacks.csv', encoding = 'latin1')

## Metodos de Reconhecimento

In [17]:
shark.head(15
          )

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
5,2018.06.03.b,03-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,Chris,M,...,NaN,"Daily Telegraph, 6/4/2018",2018.06.03.b-FlatRock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.b,2018.06.03.b,6298.0,NaN,NaN
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,...,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN
7,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,...,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN
8,2018.05.26.b,26-May-2018,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,...,"Bull shark, 6'","K.McMurray, TrackingSharks.com",2018.05.26.b-High.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.b,2018.05.26.b,6295.0,NaN,NaN
9,2018.05.26.a,26-May-2018,2018.0,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",Standing,male,M,...,NaN,"K. McMurray, Tracking Sharks.com",2018.05.26.a-DaytonaBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.a,2018.05.26.a,6294.0,NaN,NaN
10,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,...,Grey reef shark,"ABC.net.au ,05/24/2018",2018.05.24-CairnsAquarium.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24,2018.05.24,6293.0,NaN,NaN
11,2018.05.21,21-May-2018,2018.0,Unprovoked,USA,South Carolina,"Isle of Palms, Charleston County",Boogie boarding,Trey de Boer,M,...,NaN,"C. Creswell, GSAF",2018.05.21-deBoer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.21,2018.05.21,6292.0,NaN,NaN
12,2018.05.13.b,13-May-2018,2018.0,Unprovoked,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,Jei Turrell,M,...,NaN,"C. Creswell, GSAF & K. McMurray TrackingSharks...",2018.05.13.b-Turrell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.b,2018.05.13.b,6291.0,NaN,NaN
13,2018.05.13.a,13-May-2018,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,...,Invalid incident,"K. McMurray, TrackingSharks.com",2018.05.13.a-Berryman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.a,2018.05.13.a,6290.0,NaN,NaN
14,2018.05.00,May 2018,2018.0,Provoked,AUSTRALIA,Westerm Australia,Dugong Bay,Feeding sharks,Melisa Brunning,F,...,"Tawny nurse shark, 2m","Perth Now, 6/30/2018",2018.05.00-Brunning.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.00,2018.05.00,6289.0,NaN,NaN

In [8]:

shark.dtypes

Case Number                object
Date                       object
Year                      float64
Type                       object
Country                    object
Area                       object
Location                   object
Activity                   object
Name                       object
Sex                        object
Age                        object
Injury                     object
Fatal (Y/N)                object
Time                       object
Species                    object
Investigator or Source     object
pdf                        object
href formula               object
href                       object
Case Number.1              object
Case Number.2              object
original order            float64
Unnamed: 22                object
Unnamed: 23                object
dtype: object

In [42]:
filtro = shark['Unnamed: 23'].isna()


shark.loc[~filtro, :]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
4415,1952.03.30,30-Mar-1952,1952.0,Unprovoked,NETHERLANDS ANTILLES,Curacao,NaN,Went to aid of child being menaced by the shark,A.J. Eggink,M,...,"Bull shark, 2.7 m [9'] was captured & dragged ...","J. Randall, p.352 in Sharks & Survival; H.D. B...",1952.03.30-Eggink.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1952.03.30,1952.03.30,1888.0,NaN,Teramo
5840,1878.09.14.R,Reported 14-Sep-1878,1878.0,Provoked,USA,Connecticut,"Branford, New Haven County",Fishing,Captain Pattison,M,...,NaN,"St. Joseph Herald, 9/14/1878",1878.09.14.R-Pattison.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1878.09.14.R,1878.09.14.R,463.0,NaN,change filename

In [44]:
shark.shape

(25723, 24)

In [16]:
shark.info

<bound method DataFrame.info of       Case Number         Date    Year        Type    Country  \
0      2018.06.25  25-Jun-2018  2018.0     Boating        USA
1      2018.06.18  18-Jun-2018  2018.0  Unprovoked        USA
2      2018.06.09  09-Jun-2018  2018.0     Invalid        USA
3      2018.06.08  08-Jun-2018  2018.0  Unprovoked  AUSTRALIA
4      2018.06.04  04-Jun-2018  2018.0    Provoked     MEXICO
...           ...          ...     ...         ...        ...
25718         NaN          NaN     NaN         NaN        NaN
25719         NaN          NaN     NaN         NaN        NaN
25720         NaN          NaN     NaN         NaN        NaN
25721         NaN          NaN     NaN         NaN        NaN
25722          xx          NaN     NaN         NaN        NaN

                  Area                        Location     Activity  \
0           California     Oceanside, San Diego County     Paddling
1              Georgia  St. Simon Island, Glynn County     Standing
2               Hawaii                    Habush, Oahu      Surfing
3      New South Wales              Arrawarra Headland      Surfing
4               Colima                        La Ticla  Free diving
...                ...                             ...          ...
25718              NaN                             NaN          NaN
25719              NaN                             NaN          NaN
25720              NaN                             NaN          NaN
25721              NaN                             NaN          NaN
25722              NaN                             NaN          NaN

                  Name Sex   ...         Species   \
0          Julie Wolfe    F  ...      White shark
1      AdysonÂ McNeely     F  ...              NaN
2          John Denges    M  ...              NaN
3                 male    M  ...        2 m shark
4       Gustavo Ramos     M  ...  Tiger shark, 3m
...                ...  ...  ...              ...
25718              NaN  NaN  ...              NaN
25719              NaN  NaN  ...              NaN
25720              NaN  NaN  ...              NaN
25721              NaN  NaN  ...              NaN
25722              NaN  NaN  ...              NaN

               Investigator or Source                       pdf  \
0                    R. Collier, GSAF      2018.06.25-Wolfe.pdf
1      K.McMurray, TrackingSharks.com    2018.06.18-McNeely.pdf
2      K.McMurray, TrackingSharks.com     2018.06.09-Denges.pdf
3                      B. Myatt, GSAF  2018.06.08-Arrawarra.pdf
4                           A .Kipper      2018.06.04-Ramos.pdf
...                               ...                       ...
25718                             NaN                       NaN
25719                             NaN                       NaN
25720                             NaN                       NaN
25721                             NaN                       NaN
25722                             NaN                       NaN

                                            href formula  \
0      http://sharkattackfile.net/spreadsheets/pdf_di...
1      http://sharkattackfile.net/spreadsheets/pdf_di...
2      http://sharkattackfile.net/spreadsheets/pdf_di...
3      http://sharkattackfile.net/spreadsheets/pdf_di...
4      http://sharkattackfile.net/spreadsheets/pdf_di...
...                                                  ...
25718                                                NaN
25719                                                NaN
25720                                                NaN
25721                                                NaN
25722                                                NaN

                                                    href Case Number.1  \
0      http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.25
1      http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.18
2      http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.09
3      http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.08
4      http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.04
...                                                  ...           ...
25718                                                NaN           NaN
25719                                                NaN           NaN
25720                                                NaN           NaN
25721                                                NaN           NaN
25722                                                NaN           NaN

      Case Number.2 original order Unnamed: 22 Unnamed: 23
0        2018.06.25         6303.0         NaN         NaN
1        2018.06.18         6302.0         NaN         NaN
2        2018.06.09         6301.0         NaN         NaN
3        2018.06.08         6300.0         NaN         NaN
4        2018.06.04         6299.0         NaN         NaN
...             ...            ...         ...         ...
25718           NaN            NaN         NaN         NaN
25719           NaN            NaN         NaN         NaN
25720           NaN            NaN         NaN         NaN
25721           NaN            NaN         NaN         NaN
25722           NaN            NaN         NaN         NaN

[25723 rows x 24 columns]>

In [15]:
shark.describe()

              Year  original order
count  6300.000000     6309.000000
mean   1927.272381     3155.999683
std     281.116308     1821.396206
min       0.000000        2.000000
25%    1942.000000     1579.000000
50%    1977.000000     3156.000000
75%    2005.000000     4733.000000
max    2018.000000     6310.000000

In [13]:
shark.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [4]:
shark.loc[:,'Country':'Area']

         Country             Area
0            USA       California
1            USA          Georgia
2            USA           Hawaii
3      AUSTRALIA  New South Wales
4         MEXICO           Colima
...          ...              ...
25718        NaN              NaN
25719        NaN              NaN
25720        NaN              NaN
25721        NaN              NaN
25722        NaN              NaN

[25723 rows x 2 columns]

In [48]:
pd.set_option("max_rows", None)